import {
  ReceiptText,
  Plus,
  Clock,
  ChevronRight,
  FileText,
} from "lucide-react";

import {
  motion,
} from "framer-motion";

/* =========================================================
   EMPTY INVOICE
========================================================= */

const EmptyInvoice = ({
  title = "No Invoices Yet",
  description = "Your monthly transport invoices will appear here once they are generated by the administrator.",
  showAction = false,
  actionText = "Learn More",
  onAction = () => {},
  icon: CustomIcon,
  className = "",
}) => {
  const Icon =
    CustomIcon ||
    ReceiptText;

  return (
    <motion.div
      initial={{
        opacity: 0,
        y: 10,
      }}
      animate={{
        opacity: 1,
        y: 0,
      }}
      transition={{
        duration: 0.35,
      }}
      className={`
        relative
        overflow-hidden
        rounded-[26px]
        border
        border-[#EEDB99]
        bg-white
        shadow-[0_10px_28px_rgba(79,61,12,0.05)]
        ${className}
      `}
    >
      {/* =================================================
          TOP ACCENT
      ================================================= */}

      <div
        className="
          h-[4px]
          w-full
          bg-[#FFB400]
        "
      />

      {/* =================================================
          DECORATION
      ================================================= */}

      <div
        className="
          pointer-events-none
          absolute
          -right-[55px]
          -top-[45px]
          h-[145px]
          w-[145px]
          rounded-full
          bg-[#FFF0B8]
        "
      />

      <div
        className="
          pointer-events-none
          absolute
          right-[35px]
          top-[80px]
          h-[65px]
          w-[65px]
          rounded-full
          border-[13px]
          border-[#FFF3CA]
        "
      />

      {/* =================================================
          CONTENT
      ================================================= */}

      <div
        className="
          relative
          z-10
          px-5
          py-6
        "
      >
        {/* =================================================
            TOP LABEL
        ================================================= */}

        <div
          className="
            flex
            items-center
            justify-between
            gap-3
          "
        >
          <div
            className="
              flex
              items-center
              gap-2
            "
          >
            <div
              className="
                flex
                h-[34px]
                w-[34px]
                items-center
                justify-center
                rounded-[11px]
                border
                border-[#EBD483]
                bg-[#FFF3C8]
                text-[#B77D00]
              "
            >
              <ReceiptText
                size={15}
              />
            </div>

            <div>
              <p
                className="
                  text-[8px]
                  font-extrabold
                  uppercase
                  tracking-[1.6px]
                  text-[#B77D00]
                "
              >
                Billing
              </p>

              <p
                className="
                  mt-[2px]
                  text-[11px]
                  font-semibold
                  text-zinc-500
                "
              >
                Invoice Center
              </p>
            </div>
          </div>

          <div
            className="
              rounded-full
              border
              border-[#EBD483]
              bg-[#FFF3C8]
              px-3
              py-1.5
              text-[7px]
              font-extrabold
              uppercase
              text-[#936500]
            "
          >
            Empty
          </div>
        </div>

        {/* =================================================
            EMPTY STATE
        ================================================= */}

        <div
          className="
            flex
            flex-col
            items-center
            pb-3
            pt-6
            text-center
          "
        >
          {/* =================================================
              MAIN ICON
          ================================================= */}

          <motion.div
            animate={{
              y: [
                0,
                -3,
                0,
              ],
            }}
            transition={{
              duration: 2.4,
              repeat: Infinity,
              ease: "easeInOut",
            }}
            whileHover={{
              scale: 1.04,
              rotate: 2,
            }}
            className="
              relative
              flex
              h-[82px]
              w-[82px]
              items-center
              justify-center
              rounded-[24px]
              border
              border-[#E7CA69]
              bg-[#FFF0B8]
              text-[#A87200]
              shadow-[0_12px_26px_rgba(113,82,10,0.08)]
            "
          >
            <Icon
              size={35}
              strokeWidth={1.8}
            />

            {/* =================================================
                TOP DOT
            ================================================= */}

            <motion.div
              animate={{
                scale: [
                  1,
                  1.2,
                  1,
                ],
              }}
              transition={{
                duration: 1.8,
                repeat: Infinity,
              }}
              className="
                absolute
                -right-[5px]
                -top-[5px]
                h-[18px]
                w-[18px]
                rounded-full
                border-[3px]
                border-white
                bg-[#FFB400]
              "
            />

            {/* =================================================
                BOTTOM DOT
            ================================================= */}

            <div
              className="
                absolute
                -bottom-[5px]
                -left-[5px]
                h-[12px]
                w-[12px]
                rounded-full
                border-2
                border-white
                bg-[#FFE79A]
              "
            />
          </motion.div>

          {/* =================================================
              TITLE
          ================================================= */}

          <h2
            className="
              mt-5
              text-[19px]
              font-extrabold
              tracking-[-0.3px]
              text-black
            "
          >
            {title}
          </h2>

          {/* =================================================
              DESCRIPTION
          ================================================= */}

          <p
            className="
              mt-2
              max-w-[300px]
              text-[10px]
              leading-[1.65]
              text-zinc-500
            "
          >
            {description}
          </p>

          {/* =================================================
              OPTIONAL ACTION
          ================================================= */}

          {showAction && (
            <motion.button
              type="button"
              onClick={
                onAction
              }
              whileHover={{
                scale: 1.02,
              }}
              whileTap={{
                scale: 0.97,
              }}
              className="
                mt-5
                flex
                h-[46px]
                min-w-[170px]
                items-center
                justify-center
                gap-2
                rounded-[15px]
                bg-[#FFB400]
                px-5
                text-[11px]
                font-extrabold
                text-black
                shadow-[0_8px_20px_rgba(255,180,0,0.20)]
                transition
                hover:bg-[#F5AA00]
              "
            >
              <Plus
                size={16}
              />

              {actionText}

              <ChevronRight
                size={15}
              />
            </motion.button>
          )}
        </div>

        {/* =================================================
            INFORMATION
        ================================================= */}

        <div
          className="
            mt-4
            overflow-hidden
            rounded-[18px]
            border
            border-[#EEDB99]
            bg-[#FFFDF8]
          "
        >
          <InfoRow
            icon={
              <Clock
                size={15}
              />
            }
            title="Real-time Updates"
            description="Invoices appear automatically when generated."
          />

          <div
            className="
              ml-[58px]
              h-px
              bg-[#F0E5C6]
            "
          />

          <InfoRow
            icon={
              <FileText
                size={15}
              />
            }
            title="Invoice Details"
            description="Generated invoices can be opened to view complete billing details."
          />
        </div>
      </div>
    </motion.div>
  );
};

/* =========================================================
   INFO ROW
========================================================= */

function InfoRow({
  icon,
  title,
  description,
}) {
  return (
    <motion.div
      whileHover={{
        backgroundColor:
          "#FFF9E8",
      }}
      className="
        flex
        items-center
        gap-3
        px-4
        py-3
        transition
      "
    >
      {/* =================================================
          ICON
      ================================================= */}

      <motion.div
        whileHover={{
          scale: 1.06,
          rotate: 3,
        }}
        className="
          flex
          h-[34px]
          w-[34px]
          shrink-0
          items-center
          justify-center
          rounded-[11px]
          border
          border-[#EBD483]
          bg-[#FFF3C8]
          text-[#B77D00]
        "
      >
        {icon}
      </motion.div>

      {/* =================================================
          TEXT
      ================================================= */}

      <div
        className="
          min-w-0
          flex-1
        "
      >
        <p
          className="
            text-[10px]
            font-bold
            text-black
          "
        >
          {title}
        </p>

        <p
          className="
            mt-[2px]
            text-[8px]
            leading-4
            text-zinc-500
          "
        >
          {description}
        </p>
      </div>
    </motion.div>
  );
}

export default EmptyInvoice;